BoxLayout:
    orientation: 'vertical'
    Label:
        text: 'Level'
        font_size: 150
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Board_1'
            font_size: 150
        Label:
            text: 'Board_1'
            font_size: 150
        Label:
            text: 'Board_1'
            font_size: 150
    Label:
        text: 'Instructions'
        font_size: 150
